version: "3.8"

services:
  MS_SQL:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ms-server-volume:/var/opt/mssql
    expose:
      - "1433"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - "8003:3000"
    volumes:
      - my-db:/root/.dbgate
    environment:
      CONNECTIONS: con1

      LABEL_con1: MsSql
      SERVER_con1: MS_SQL
      USER_con1: SA
      PASSWORD_con1: 1Secure*Password1
      PORT_con1: 1433
      ENGINE_con1: mssql@dbgate-plugin-mssql
volumes:
  my-db:
  ms-server-volume: